config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  get 'pages/welcome'

  get 'pages/contact'
  
  get '/search/:search_term' => 'cards#search'



  resources :histories do
    collection do
      post :add_rep
    end
  end
  devise_for :users
  resources :cards do
    
    collection do
      # post :next_card
      # post :previous_card
      post :choiceA_selected
      post :choiceB_selected
      post :choiceC_selected
      post :choiceD_selected
      post :change_level_to_easy
      post :change_level_to_medium
      post :change_level_to_hard
      
      post:reset_rep
      
      post :list_all
      
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# root to: 'cards#index'
# root to: 'devise/sessions#new'
root to: 'pages#welcome'
 post 'cards/choiceA/:level' => 'cards#choiceA'
end

app/models/objective.rb
class Objective < ApplicationRecord
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  
  before_action :require_same_user, only: [:edit, :delete]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      params.require(:objective).permit(:title, :completed_at, :category, :user_id)
    end
    
    def require_user
        if !user_signed_in?
            flash[:danger]='you need to log in first'
            redirect_to pages_welcome_path
        end
    end
    
    def require_same_user
        if user_signed_in? and @card.user_id != current_user.id
            flash[:danger]='you are not the same user'
            redirect_to login_path
        end
    end
    
    
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_for(objective) do |f| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :completed_at %>
    <%= f.datetime_select :completed_at %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<h1>Editing Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Show', @objective %> |
<%= link_to 'Back', objectives_path %>

app/views/objectives/index.html.erb
<%=content_for :title, "Objectives"%>

<p id="notice"><%= notice %></p>

<h1>Objectives</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Completed at</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= objective.title %></td>
        <td><%= objective.completed_at %></td>
        <td><%= objective.category %></td>
        <td><%= objective.user_id %></td>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective', new_objective_path %>

app/views/objectives/new.html.erb
<h1>New Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @objective.title %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @objective.completed_at %>
</p>

<p>
  <strong>Category:</strong>
  <%= @objective.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @objective.user_id %>
</p>

<%= link_to 'Edit', edit_objective_path(@objective) %> |
<%= link_to 'Back', objectives_path %>