config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  get 'pages/welcome'

  get 'pages/contact'
  
  get '/search/:search_term' => 'cards#search'



  resources :histories do
    collection do
      post :add_rep
    end
  end
  devise_for :users
  resources :cards do
    
    collection do
      # post :next_card
      # post :previous_card
      post :choiceA_selected
      post :choiceB_selected
      post :choiceC_selected
      post :choiceD_selected
      post :change_level_to_easy
      post :change_level_to_medium
      post :change_level_to_hard
      
      post:reset_rep
      
      post :list_all
      
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# root to: 'cards#index'
# root to: 'devise/sessions#new'
root to: 'pages#welcome'
 post 'cards/choiceA/:level' => 'cards#choiceA'
end

app/models/history.rb
class History < ApplicationRecord
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  
  before_action :require_same_user, only: [:edit, :delete]



def add_rep
  # @h=History.create(date: Date.yesterday, reps: 10)
  # @h = History.all.where(:date => Date.today).first
  @h = History.all.where(:date => Time.zone.now.to_date).first
  if !@h.nil?
    @h.repCount +=1
    @h.save
  else
    @h=History.create(date: Time.zone.now.to_date, repCount: 1) #instead of Date.today
  end
  # @h = History.find(1)
  # @h.date = 
  # @h.rep +=1
  # @h.save
  redirect_to histories_path
end

  # GET /histories
  # GET /histories.json
  def index
    # @histories = History.all
    # @histories = History.all.where(:date => Date.today, :user_id => current_user.id.to_i).first
    @histories = History.all.where(:user_id => current_user.id.to_i)
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
      session[:repCount] ||=@history.repCount
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:date, :repCount, :user_id)
    end
    
    
    def require_user
        if !user_signed_in?
            flash[:danger]='you need to log in first'
            redirect_to pages_welcome_path
        end
    end
    
    def require_same_user
        if user_signed_in? and @card.user_id != current_user.id
            flash[:danger]='you are not the same user'
            redirect_to login_path
        end
    end
    
    
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(history) do |f| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :repCount %>
    <%= f.number_field :repCount %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<%=content_for :title, "History"%>
<p id="notice"><%= notice %></p>

<div class='well'>

<h1>History</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Rep count</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.date %></td>
        <td><%= history.repCount %></td>
        <td><%=User.find(history.user_id).email%>(<%= history.user_id %>)</td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>
</div>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @history.date %>
</p>

<p>
  <strong>Repcount:</strong>
  <%= @history.repCount %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user_id %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>