config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  get 'pages/welcome'

  get 'pages/contact'
  
  get '/search/:search_term' => 'cards#search'



  resources :histories do
    collection do
      post :add_rep
    end
  end
  devise_for :users
  resources :cards do
    
    collection do
      # post :next_card
      # post :previous_card
      post :choiceA_selected
      post :choiceB_selected
      post :choiceC_selected
      post :choiceD_selected
      post :change_level_to_easy
      post :change_level_to_medium
      post :change_level_to_hard
      
      post:reset_rep
      
      post :list_all
      
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# root to: 'cards#index'
# root to: 'devise/sessions#new'
root to: 'pages#welcome'
 post 'cards/choiceA/:level' => 'cards#choiceA'
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    # set_primary_key :id
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  
  before_action :require_same_user, only: [:edit, :delete]

  # before_action :initialize

def list_all
   session[:correct_in_a_row] ||= 0
    session[:todays_rep_count] ||= 0
    start_card
    
    @history = History.all.where(:user_id => current_user.id.to_i, :date => Date.today).first
    # session[:todays_rep_count] ||= 0
    
    if @history.nil?
      # @history=History.create(email: 'dean@gmail.com', encrypted_password: '123456')
      @history=History.create(date: Date.today, repCount: 0)
      # @history.repCount =0
      # @history.save
    end
    
    # @card = Card.all.where("level = ? and user_id =? ", "Hard" , current_user.id).order(:updated_at).first
# session[:current_id] = @card.id
    session[:current_id] ||= 1
    session[:choiceA_id] ||= 1
    session[:choiceB_id] ||= 1
    session[:choiceC_id] ||= 1
    session[:choiceD_id] ||= 1
    session[:todays_rep_count] ||=0
    gen_rand_ids()
 # generate 4 unique random numbers between 1 and 5 in an array
      # @my_array=(1..5).to_a.sample(4)
      # @my_array = Array.new
      @my_array2 = Card.all.where(:user_id => current_user.id.to_i)
      # @my_array =Card.order("RANDOM()").limit(4).where(:user_id => current_user.id.to_i).where.not(:id => session[:current_id] )
       @my_array =Card.order("RANDOM()").limit(4).where(:user_id => current_user.id.to_i).where(:category => Card.find(session[:current_id]).category).where.not(:id => session[:current_id] )
              
              
              rand_index = 0 + rand(4) 
          @my_array[rand_index ].id = session[:current_id].to_i
      # if !@my_array.include? session[:current_id].to_i
      #   rand_index = 0 + rand(4) 
      #     @my_array[rand_index ].id = session[:current_id].to_i
      # end
    session[:choiceA_id] = @my_array[0].id
    session[:choiceB_id] = @my_array[1].id
    session[:choiceC_id] = @my_array[2].id
    session[:choiceD_id] = @my_array[3].id 
    
    # @card = Card.find(session[:current_id] )
    # @card.level = session[:card_level]
    # @card.save
    
    
    
    @cards = Card.all.where(:user_id => current_user.id.to_i)
  # redirect_back(fallback_location: objectives_path)
  
end

def search 
  # @result=params[:search_term1]
   @result = Card.all.where(:question => params[:search_term1]).order(:updated_at).first
end

def choiceA
  card = Card.find(session[:current_id] )
  # card.level = params[:level]
  card.save
  redirect_to cards_path
    
end

def change_level_to_easy
  card = Card.find(session[:current_id] )
  card.record_timestamps = false
  card.level = "Easy"
  card.save
  redirect_to cards_path
end

def change_level_to_medium
  card = Card.find(session[:current_id] )
  card.record_timestamps = false
  card.level = "Medium"
  card.save
  redirect_to cards_path
end

def change_level_to_hard
  card = Card.find(session[:current_id] )
  card.record_timestamps = false
  card.level = "Hard"
  card.save
  redirect_to cards_path
end


def wrong_answer
  card = Card.find(session[:current_id] )
  card.record_timestamps = false
  card.level = "Hard"
  card.save
  session[:correct_in_a_row] = 0
  # session[:todays_rep_count] -= 2
end


def choiceA_selected
  if session[:current_id] == session[:choiceA_id]
  # flash[:success] = "Correct!"
    next_card()
  else
    flash[:danger] = "Inorrect!"
    wrong_answer
   redirect_to cards_path
  end
end

def choiceB_selected
  if session[:current_id] == session[:choiceB_id]
  # flash[:success] = "Correct!"
    next_card()
  else
    flash[:danger] = "Inorrect!"
    wrong_answer
    redirect_to cards_path
  end
end

def choiceC_selected
  if session[:current_id] == session[:choiceC_id]
  # flash[:success] = "Correct!"
    next_card()
  else
    flash[:danger] = "Inorrect!"
    wrong_answer
    redirect_to cards_path
  end
end

def choiceD_selected
  if session[:current_id] == session[:choiceD_id]
  # flash[:success] = "Correct!"
    next_card()
  else
    flash[:danger] = "Inorrect!"
    wrong_answer
    redirect_to cards_path
  end
end

def reset_rep
  Card.all.each do |card|
    card.rep = 0
    # card.user_id=2
    card.save
  end
  session[:todays_rep_count] = 0
  redirect_to cards_path
end

# def next_card
#   card = Card.find(session[:current_id] )
#   card.rep +=1
#   # session[:card_level] = params[:level]
#   # card.level = session[:card_level]
#   card.save
  
#     if session[:current_id] < 5
#         session[:current_id] +=1
#     else
#         session[:current_id] =1
#     end
#     session[:todays_rep_count] +=1
    
#     redirect_to cards_path
# end

def add_rep_to_history
  # @h=History.create(date: Date.yesterday, reps: 10)
  @h = History.all.where(:date => Date.today, :user_id => current_user.id.to_i).first
  if !@h.nil?
    @h.repCount +=1
    @h.save
  else
    @h=History.create(date: Date.today, repCount: 1, :user_id => current_user.id.to_i)
  end
  # redirect_to histories_path
end

def increment_card_rep
    card = Card.find(session[:current_id] )
    card.rep +=1
    card.save
    add_rep_to_history
    
    session[:correct_in_a_row] +=1
  # session[:card_level] = params[:level]
  # card.level = session[:card_level]

end

def start_card
    if session[:todays_rep_count] % 5 ==0 #5, 10,9 12 15
        @card = Card.all.where("level = ? and user_id =? ", "Medium" , current_user.id).order(:updated_at).first
# User.where("users.name = ? OR users.name = ?", request.requester, request.regional_sales_mgr)
# User.where(["name = ? and email = ?", "Joe", "joe@example.com"])

    elsif session[:todays_rep_count] %2 == 0 #0,2,4
      # @card = Card.all.where(:level => 'Hard').order(:updated_at).first
      @card = Card.all.where("level = ? and user_id =? ", "Hard" , current_user.id).order(:updated_at).first

    else                                     #5 7 11 13 17
    @card = Card.all.where("level = ? and user_id =? ", "Easy" , current_user.id).order(:updated_at).first

        # @card = Card.all.where(:level => 'Easy').order(:updated_at).first
    end
    if @card.nil?
      @card = Card.all.where(:user_id => current_user.id).order(:updated_at).first
    end
    
    
      # @card = Card.all.where.not("category ='Math'").where(:user_id => current_user.id).order(:updated_at).first
     
    
    session[:current_id] = @card.id
 
  
end

def next_card
    increment_card_rep
    
    if session[:todays_rep_count] % 5 ==0 #5, 10,9 12 15
        @card = Card.all.where("level = ? and user_id =? ", "Medium" , current_user.id).order(:updated_at).first
# User.where("users.name = ? OR users.name = ?", request.requester, request.regional_sales_mgr)
# User.where(["name = ? and email = ?", "Joe", "joe@example.com"])

    elsif session[:todays_rep_count] %2 == 0 #0,2,4
      # @card = Card.all.where(:level => 'Hard').order(:updated_at).first
      @card = Card.all.where("level = ? and user_id =? ", "Hard" , current_user.id).order(:updated_at).first

    else                                     #5 7 11 13 17
    @card = Card.all.where("level = ? and user_id =? ", "Easy" , current_user.id).order(:updated_at).first

        # @card = Card.all.where(:level => 'Easy').order(:updated_at).first
    end
    if @card.nil?
      @card = Card.all.where(:user_id => current_user.id).order(:updated_at).first
    end
    session[:current_id] = @card.id
    session[:todays_rep_count] +=1
 
    redirect_to cards_path
end

  def modifyAll
     Card.all.each do |c|
      if c.category==""
        c.category='Vocab'
        c.save
      end
      
  end
  end


  # GET /cards
  # GET /cards.json
  def index
    session[:correct_in_a_row] ||= 0
    session[:todays_rep_count] ||= 0
    start_card
    
    @history = History.all.where(:user_id => current_user.id.to_i, :date => Date.today).first
    # session[:todays_rep_count] ||= 0
    
    if @history.nil?
      # @history=History.create(email: 'dean@gmail.com', encrypted_password: '123456')
      @history=History.create(date: Date.today, repCount: 0)
      # @history.repCount =0
      # @history.save
    end
    
    # @card = Card.all.where("level = ? and user_id =? ", "Hard" , current_user.id).order(:updated_at).first
# session[:current_id] = @card.id
    session[:current_id] ||= 1
    session[:choiceA_id] ||= 1
    session[:choiceB_id] ||= 1
    session[:choiceC_id] ||= 1
    session[:choiceD_id] ||= 1
    session[:todays_rep_count] ||=0
    gen_rand_ids()
 # generate 4 unique random numbers between 1 and 5 in an array
      # @my_array=(1..5).to_a.sample(4)
      # @my_array = Array.new
      @my_array2 = Card.all.where(:user_id => current_user.id.to_i)
      # @my_array =Card.order("RANDOM()").limit(4).where(:user_id => current_user.id.to_i).where.not(:id => session[:current_id] )
       @my_array =Card.order("RANDOM()").limit(4).where(:user_id => current_user.id.to_i).where(:category => Card.find(session[:current_id]).category).where.not(:id => session[:current_id] )
              
              
              rand_index = 0 + rand(4) 
          @my_array[rand_index ].id = session[:current_id].to_i
      # if !@my_array.include? session[:current_id].to_i
      #   rand_index = 0 + rand(4) 
      #     @my_array[rand_index ].id = session[:current_id].to_i
      # end
    session[:choiceA_id] = @my_array[0].id
    session[:choiceB_id] = @my_array[1].id
    session[:choiceC_id] = @my_array[2].id
    session[:choiceD_id] = @my_array[3].id 
    
    # @card = Card.find(session[:current_id] )
    # @card.level = session[:card_level]
    # @card.save
    
    
    
    @cards = Card.all.where(:user_id => current_user.id.to_i)
  # redirect_back(fallback_location: objectives_path)
  
  end
  
  def gen_rand_ids
   
    # my_array = Array.new(4) { rand(1...9) }
    #if array contains current_id, do nothing
    #else n=random number between 1 and 3
    #replace the n element with current_id

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_area :question %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area :answer %>
  </div>

  <div class="field">
    <%= f.label :media %>
    <%= f.text_area :media %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :rep %>
    <%= f.number_field :rep %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.text_area :level %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<%=content_for :title, "Drill"%>
<head>

</head>


<body>
  
  
  <%if @cards.count > 5%>

<!--<h1>Cards</h1>-->

<!--<p id='debug'><%=@card.level%></p>-->
<div class='well'>
<!-- <div class='italic_text'>Points in a row:  <%=session[:correct_in_a_row]%></div>-->
<!--<strong>Today's Rep Count: <%=@history.repCount%> </strong>-->
<!--<strong><div class='count'><%=session[:todays_rep_count]%></div></strong>-->
<!--<strong><div class='count'><%=@history.repCount%></div></strong>-->


<div class='score'>
  <%=link_to "Score: #{@history.repCount}", histories_path%>
</div>





<!--<%= @my_array.join ' ' %> -->
<!--<p>session[:current_id] <%=session[:current_id]%></p>-->
<!--<p>session[:choiceA_id] <%=session[:choiceA_id]%> </p>-->
<!--<p>session[:choiceB_id] <%=session[:choiceB_id]%> </p>-->
<!--<p>session[:choiceC_id] <%=session[:choiceC_id]%> </p>-->
<!--<p>session[:choiceD_id] <%=session[:choiceD_id]%> </p>-->





  <%if @card.level=="Easy"%>
    <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default active"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default"  %>
  </div>
  <%elsif @card.level=="Medium"%>
   <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default active"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default"  %>
  </div>
  <%else%>
    <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default active"   %>
  </div>
  <%end%>


  
  <hr/>



  <div id='question'>
  <strong > <%=@card.question %> </strong>
</div>


<br/>
<div class='choice_buttons center-block'>
 
  <%=link_to "#{Card.find(session[:choiceA_id]).answer}", choiceA_selected_cards_path, class: 'btn btn-primary btn-block', method: :post%><br/>
  <%=link_to "#{Card.find(session[:choiceB_id]).answer}", choiceB_selected_cards_path, class: 'btn btn-primary btn-block', method: :post%><br/>
  <%=link_to "#{Card.find(session[:choiceC_id]).answer}", choiceC_selected_cards_path, class: 'btn btn-primary btn-block', method: :post%><br/>
  <%=link_to "#{Card.find(session[:choiceD_id]).answer}", choiceD_selected_cards_path, class: 'btn btn-primary btn-block', method: :post%><br/>

   </div>


<br/>


<br>
<%else%>
</br>
<div class='count'>You have <%=@cards.count%> cards. You need at least 4 cards in the database</div>
<%end%>



</body>

app/views/cards/list_all.html.erb
<%=content_for :title, "List All"%>
<head>

</head>


<body>
  Date.today: <%=Date.today%><br/>
Time.zone.now.to_date: <%=Time.zone.now.to_date%>
 <!--<li><%=link_to "Today's Count: #{session[:correct_in_a_row]}", histories_path%></li>-->
  
  <%if @cards.count > 5%>

<!--<h1>Cards</h1>-->

<!--<p id='debug'><%=@card.level%></p>-->

<strong>Today's Rep Count:  </strong><br/><br/>
<!--<strong><div class='count'><%=session[:todays_rep_count]%></div></strong>-->
<strong><div class='count'><%=@history.repCount%></div></strong>


<br/>
<strong>Points in a Row:  </strong> <%=session[:correct_in_a_row]%>



<!--<%= @my_array.join ' ' %> -->
<!--<p>session[:current_id] <%=session[:current_id]%></p>-->
<!--<p>session[:choiceA_id] <%=session[:choiceA_id]%> </p>-->
<!--<p>session[:choiceB_id] <%=session[:choiceB_id]%> </p>-->
<!--<p>session[:choiceC_id] <%=session[:choiceC_id]%> </p>-->
<!--<p>session[:choiceD_id] <%=session[:choiceD_id]%> </p>-->





  <%if @card.level=="Easy"%>
    <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default active"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default"  %>
  </div>
  <%elsif @card.level=="Medium"%>
   <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default active"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default"  %>
  </div>
  <%else%>
    <div class='level_buttons'>
  <%=link_to 'Easy',change_level_to_easy_cards_path(level: 'Easy'), method: :post, id:"easy", class:"btn btn-default"   %>
  <%=link_to 'Medium',change_level_to_medium_cards_path(level: 'Medium'), method: :post, id:"medium", class:"btn btn-default"  %>
  <%=link_to 'Hard',change_level_to_hard_cards_path(level: 'Hard'), method: :post, id:"hard", class:"btn btn-default active"   %>
  </div>
  <%end%>
  <br/><br/>

  


<br/><br/>


  <div id='question'>
  <strong > <%=@card.question %> </strong>
</div>


<br/><br/>
<div class='choice_buttons'>
  <%=link_to "#{Card.find(session[:choiceA_id]).answer}", choiceA_selected_cards_path, class: 'btn btn-primary', method: :post%>
  <%=link_to "#{Card.find(session[:choiceB_id]).answer}", choiceB_selected_cards_path, class: 'btn btn-primary', method: :post%>
  <%=link_to "#{Card.find(session[:choiceC_id]).answer}", choiceC_selected_cards_path, class: 'btn btn-primary', method: :post%>
  <%=link_to "#{Card.find(session[:choiceD_id]).answer}", choiceD_selected_cards_path, class: 'btn btn-primary', method: :post%>
   </div>


<br/>
<%=link_to 'Reinico Reps', reset_rep_cards_path, class: 'btn btn-success', method: :post%>

<table class='table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Media</th>
      <th>Comment</th>
      <th>Rep</th>
      <th>Level</th>
      <th>Category</th>
      <th>User</th>
      <th>Updated At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.id %></td>
        <td><%= card.question %></td>
        <td><%= card.answer %></td>
        <td><%= card.media %></td>
        <td><%= card.comment %></td>
        <td><%= card.rep %></td>
        <td><%= card.level %></td>
        <td><%= card.category %></td>
        <td><%= card.user_id %></td>
        <td><%= card.updated_at.in_time_zone('Eastern Time (US & Canada)').strftime("%I:%M:%S:%p %m-%d-%y") %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%else%>
</br>
<div class='count'>You have <%=@cards.count%> cards. You need at least 4 cards in the database</div>
<%end%>
<%= link_to 'New Card', new_card_path %>



</body>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/search.html.erb
<%=@result.id%><br/>
<%=@result.question%><br/>
<%=@result.answer%><br/>

app/views/cards/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @card.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @card.answer %>
</p>

<p>
  <strong>Media:</strong>
  <%= @card.media %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @card.comment %>
</p>

<p>
  <strong>Rep:</strong>
  <%= @card.rep %>
</p>

<p>
  <strong>Level:</strong>
  <%= @card.level %>
</p>

<p>
  <strong>Category:</strong>
  <%= @card.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @card.user_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>