config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  get 'pages/welcome'

  get 'pages/contact'
  
  get '/search/:search_term' => 'cards#search'



  resources :histories do
    collection do
      post :add_rep
    end
  end
  devise_for :users
  resources :cards do
    
    collection do
      # post :next_card
      # post :previous_card
      post :choiceA_selected
      post :choiceB_selected
      post :choiceC_selected
      post :choiceD_selected
      post :change_level_to_easy
      post :change_level_to_medium
      post :change_level_to_hard
      
      post:reset_rep
      
      post :list_all
      
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# root to: 'cards#index'
# root to: 'devise/sessions#new'
root to: 'pages#welcome'
 post 'cards/choiceA/:level' => 'cards#choiceA'
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class='container'> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#" >LM</a>-->
      <a class="navbar-brand" href=<%= root_path %>>
  
      <img src="<%= asset_path( 'LM3.png' ) %>" style="display: inline-block; height: 30px"/>
      <!--<img src="<%= asset_path( 'LearningMachine.png' ) %>" style="display: inline-block; height: 30px"/>-->
      
      
      <span style="display: inline-block;"></span>
    </a>
      
      <!--https://goo.gl/iNPLPf-->
      <!--<a href="#" class="pull-left"><img src="MixerNoSends.png"></a> -->
      <!--<img src="/LearningMachine_04_24_17/app/assets/images/LearningMachineLogo.png">-->
    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Cards<span class="sr-only">(current)</span></a></li>-->


        <li><%=link_to "Drill", cards_path%></li>
        <li><%=link_to "History", histories_path%></li>

        
    
        
         <%if !current_user.nil? && current_user.id==1%>
        <li><%=link_to "Objectives", objectives_path%></li>
        <li><%=link_to "List All", list_all_cards_path, method: :post%></li>
       
   <%end%>
        
        <li></li>

        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Instruments <span class="caret"></span></a>-->
        <!--  <ul class="dropdown-menu">-->
        <!--      <li><%=link_to "cards", cards_path%></li>-->
        <!--      <li role="separator" class="divider"></li>-->
        <!--      <li><a href="#">Link</a></li>-->

        <!--  </ul>-->
        <!--</li>-->
        
        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gritty<span class="caret"></span></a>-->
        <!--      <ul class="dropdown-menu">-->
        <!--        <li><%=link_to "cards", cards_path%></li>-->
        <!--        <li><%=link_to "cards", cards_path%></li>-->
        <!--        <li role="separator" class="divider"></li>-->
        <!--      <li><a href="#">Link</a></li>-->

        <!--  </ul>-->
        <!--</li>-->
        
        
        
        
      </ul>
      <!--<form action="/search/:name" class="navbar-form navbar-left" role="search">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" name="search_term1"  class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" name="search_btn"  class="btn btn-default">Submit</button>-->
      <!--</form>-->
      
  <!--    <div class='row'>-->
  <!--<div class='col-xs-2'> -->
  <!--    <%=form_for(:session, url: "", class:"navbar-form navbar-left", role:"search") do |f|%>-->
  <!--          <%=f.text_field(:entered_qty, class:"form-control", placeholder:"Search")%>-->
  <!--              <%=button_tag(type: :submit, class:'btn btn-default') do %>-->
  <!--              <%end%>-->
  <!--          <%end%>-->
  <!--      </div>-->
  <!--    </div>-->

      <ul class="nav navbar-nav navbar-right">
         <%if !user_signed_in?%>
            <li><%=link_to "Sign Up", new_user_registration_path%></li>
            <li><%=link_to "Sign In", new_user_session_path%></li>
        <%else%>
            <li><%=link_to "#{current_user.email}", destroy_user_session_path, method: :delete%></li>
            <li><%=link_to "Log Out", destroy_user_session_path, method: :delete%></li>
  <% end%>
      </ul>
    </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Font+Name">
<link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>


<!DOCTYPE html>
<html>
  <head>
    


</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    showMathMenu: false
  });
</script>

<script type="text/javascript"
   src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML&delayStartupUntil=configured">
</script>
  
<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function () {
       document.getElementById("question").style.visibility = "visible";
      // alert('Hello');
    });
 </script>
    
    
    <!--<title>Rails - LearningMachine042417</title>-->
    <title><%=(yield(:title) + " - " unless yield(:title).blank?).to_s + "Learning Machine"   %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  





  </head>
 
  <body>


    
    
    
        <%=render 'layouts/navigation'%>
       <div class='container'>   
          <div id='flash'>
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
          </div>
        <%=render 'layouts/flash'%>
    <%= yield %>
      </div>
  </body>
  
  <script>
      MathJax.Hub.Typeset();
</script>
  
  
</html>



 

 <script>
$(document).ready(function(){
        // $("#question").fadeIn(3000).removeClass('hidden');
        $("#question").fadeIn(2000);
});
</script>

<footer>
  <script type="text/javascript">
  MathJax.Hub.Configured()
</script>
</footer>